// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	teamvault "github.com/Seibert-Data/teamvault-cli/v5/pkg"
)

type Keychain struct {
	ReadPasswordStub        func(context.Context, teamvault.Url) (teamvault.Password, error)
	readPasswordMutex       sync.RWMutex
	readPasswordArgsForCall []struct {
		arg1 context.Context
		arg2 teamvault.Url
	}
	readPasswordReturns struct {
		result1 teamvault.Password
		result2 error
	}
	readPasswordReturnsOnCall map[int]struct {
		result1 teamvault.Password
		result2 error
	}
	WritePasswordStub        func(context.Context, teamvault.Url, teamvault.Password) error
	writePasswordMutex       sync.RWMutex
	writePasswordArgsForCall []struct {
		arg1 context.Context
		arg2 teamvault.Url
		arg3 teamvault.Password
	}
	writePasswordReturns struct {
		result1 error
	}
	writePasswordReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Keychain) ReadPassword(arg1 context.Context, arg2 teamvault.Url) (teamvault.Password, error) {
	fake.readPasswordMutex.Lock()
	ret, specificReturn := fake.readPasswordReturnsOnCall[len(fake.readPasswordArgsForCall)]
	fake.readPasswordArgsForCall = append(fake.readPasswordArgsForCall, struct {
		arg1 context.Context
		arg2 teamvault.Url
	}{arg1, arg2})
	stub := fake.ReadPasswordStub
	fakeReturns := fake.readPasswordReturns
	fake.recordInvocation("ReadPassword", []interface{}{arg1, arg2})
	fake.readPasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Keychain) ReadPasswordCallCount() int {
	fake.readPasswordMutex.RLock()
	defer fake.readPasswordMutex.RUnlock()
	return len(fake.readPasswordArgsForCall)
}

func (fake *Keychain) ReadPasswordCalls(stub func(context.Context, teamvault.Url) (teamvault.Password, error)) {
	fake.readPasswordMutex.Lock()
	defer fake.readPasswordMutex.Unlock()
	fake.ReadPasswordStub = stub
}

func (fake *Keychain) ReadPasswordArgsForCall(i int) (context.Context, teamvault.Url) {
	fake.readPasswordMutex.RLock()
	defer fake.readPasswordMutex.RUnlock()
	argsForCall := fake.readPasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Keychain) ReadPasswordReturns(result1 teamvault.Password, result2 error) {
	fake.readPasswordMutex.Lock()
	defer fake.readPasswordMutex.Unlock()
	fake.ReadPasswordStub = nil
	fake.readPasswordReturns = struct {
		result1 teamvault.Password
		result2 error
	}{result1, result2}
}

func (fake *Keychain) ReadPasswordReturnsOnCall(i int, result1 teamvault.Password, result2 error) {
	fake.readPasswordMutex.Lock()
	defer fake.readPasswordMutex.Unlock()
	fake.ReadPasswordStub = nil
	if fake.readPasswordReturnsOnCall == nil {
		fake.readPasswordReturnsOnCall = make(map[int]struct {
			result1 teamvault.Password
			result2 error
		})
	}
	fake.readPasswordReturnsOnCall[i] = struct {
		result1 teamvault.Password
		result2 error
	}{result1, result2}
}

func (fake *Keychain) WritePassword(arg1 context.Context, arg2 teamvault.Url, arg3 teamvault.Password) error {
	fake.writePasswordMutex.Lock()
	ret, specificReturn := fake.writePasswordReturnsOnCall[len(fake.writePasswordArgsForCall)]
	fake.writePasswordArgsForCall = append(fake.writePasswordArgsForCall, struct {
		arg1 context.Context
		arg2 teamvault.Url
		arg3 teamvault.Password
	}{arg1, arg2, arg3})
	stub := fake.WritePasswordStub
	fakeReturns := fake.writePasswordReturns
	fake.recordInvocation("WritePassword", []interface{}{arg1, arg2, arg3})
	fake.writePasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Keychain) WritePasswordCallCount() int {
	fake.writePasswordMutex.RLock()
	defer fake.writePasswordMutex.RUnlock()
	return len(fake.writePasswordArgsForCall)
}

func (fake *Keychain) WritePasswordCalls(stub func(context.Context, teamvault.Url, teamvault.Password) error) {
	fake.writePasswordMutex.Lock()
	defer fake.writePasswordMutex.Unlock()
	fake.WritePasswordStub = stub
}

func (fake *Keychain) WritePasswordArgsForCall(i int) (context.Context, teamvault.Url, teamvault.Password) {
	fake.writePasswordMutex.RLock()
	defer fake.writePasswordMutex.RUnlock()
	argsForCall := fake.writePasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Keychain) WritePasswordReturns(result1 error) {
	fake.writePasswordMutex.Lock()
	defer fake.writePasswordMutex.Unlock()
	fake.WritePasswordStub = nil
	fake.writePasswordReturns = struct {
		result1 error
	}{result1}
}

func (fake *Keychain) WritePasswordReturnsOnCall(i int, result1 error) {
	fake.writePasswordMutex.Lock()
	defer fake.writePasswordMutex.Unlock()
	fake.WritePasswordStub = nil
	if fake.writePasswordReturnsOnCall == nil {
		fake.writePasswordReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writePasswordReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Keychain) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Keychain) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ teamvault.Keychain = new(Keychain)
