// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	teamvault "github.com/Seibert-Data/teamvault-cli/v5/pkg"
)

type Writer struct {
	CreateStub        func(context.Context, teamvault.CreateSecret) (teamvault.Key, teamvault.ApiUrl, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 teamvault.CreateSecret
	}
	createReturns struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}
	createReturnsOnCall map[int]struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}
	GeneratePasswordStub        func(context.Context) (teamvault.Password, error)
	generatePasswordMutex       sync.RWMutex
	generatePasswordArgsForCall []struct {
		arg1 context.Context
	}
	generatePasswordReturns struct {
		result1 teamvault.Password
		result2 error
	}
	generatePasswordReturnsOnCall map[int]struct {
		result1 teamvault.Password
		result2 error
	}
	UpdateStub        func(context.Context, teamvault.Key, teamvault.UpdateSecret) (teamvault.Key, teamvault.ApiUrl, error)
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 teamvault.Key
		arg3 teamvault.UpdateSecret
	}
	updateReturns struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}
	updateReturnsOnCall map[int]struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Writer) Create(arg1 context.Context, arg2 teamvault.CreateSecret) (teamvault.Key, teamvault.ApiUrl, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 teamvault.CreateSecret
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *Writer) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *Writer) CreateCalls(stub func(context.Context, teamvault.CreateSecret) (teamvault.Key, teamvault.ApiUrl, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *Writer) CreateArgsForCall(i int) (context.Context, teamvault.CreateSecret) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Writer) CreateReturns(result1 teamvault.Key, result2 teamvault.ApiUrl, result3 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}{result1, result2, result3}
}

func (fake *Writer) CreateReturnsOnCall(i int, result1 teamvault.Key, result2 teamvault.ApiUrl, result3 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 teamvault.Key
			result2 teamvault.ApiUrl
			result3 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}{result1, result2, result3}
}

func (fake *Writer) GeneratePassword(arg1 context.Context) (teamvault.Password, error) {
	fake.generatePasswordMutex.Lock()
	ret, specificReturn := fake.generatePasswordReturnsOnCall[len(fake.generatePasswordArgsForCall)]
	fake.generatePasswordArgsForCall = append(fake.generatePasswordArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GeneratePasswordStub
	fakeReturns := fake.generatePasswordReturns
	fake.recordInvocation("GeneratePassword", []interface{}{arg1})
	fake.generatePasswordMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Writer) GeneratePasswordCallCount() int {
	fake.generatePasswordMutex.RLock()
	defer fake.generatePasswordMutex.RUnlock()
	return len(fake.generatePasswordArgsForCall)
}

func (fake *Writer) GeneratePasswordCalls(stub func(context.Context) (teamvault.Password, error)) {
	fake.generatePasswordMutex.Lock()
	defer fake.generatePasswordMutex.Unlock()
	fake.GeneratePasswordStub = stub
}

func (fake *Writer) GeneratePasswordArgsForCall(i int) context.Context {
	fake.generatePasswordMutex.RLock()
	defer fake.generatePasswordMutex.RUnlock()
	argsForCall := fake.generatePasswordArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Writer) GeneratePasswordReturns(result1 teamvault.Password, result2 error) {
	fake.generatePasswordMutex.Lock()
	defer fake.generatePasswordMutex.Unlock()
	fake.GeneratePasswordStub = nil
	fake.generatePasswordReturns = struct {
		result1 teamvault.Password
		result2 error
	}{result1, result2}
}

func (fake *Writer) GeneratePasswordReturnsOnCall(i int, result1 teamvault.Password, result2 error) {
	fake.generatePasswordMutex.Lock()
	defer fake.generatePasswordMutex.Unlock()
	fake.GeneratePasswordStub = nil
	if fake.generatePasswordReturnsOnCall == nil {
		fake.generatePasswordReturnsOnCall = make(map[int]struct {
			result1 teamvault.Password
			result2 error
		})
	}
	fake.generatePasswordReturnsOnCall[i] = struct {
		result1 teamvault.Password
		result2 error
	}{result1, result2}
}

func (fake *Writer) Update(arg1 context.Context, arg2 teamvault.Key, arg3 teamvault.UpdateSecret) (teamvault.Key, teamvault.ApiUrl, error) {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 teamvault.Key
		arg3 teamvault.UpdateSecret
	}{arg1, arg2, arg3})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2, arg3})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *Writer) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *Writer) UpdateCalls(stub func(context.Context, teamvault.Key, teamvault.UpdateSecret) (teamvault.Key, teamvault.ApiUrl, error)) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *Writer) UpdateArgsForCall(i int) (context.Context, teamvault.Key, teamvault.UpdateSecret) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Writer) UpdateReturns(result1 teamvault.Key, result2 teamvault.ApiUrl, result3 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}{result1, result2, result3}
}

func (fake *Writer) UpdateReturnsOnCall(i int, result1 teamvault.Key, result2 teamvault.ApiUrl, result3 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 teamvault.Key
			result2 teamvault.ApiUrl
			result3 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 teamvault.Key
		result2 teamvault.ApiUrl
		result3 error
	}{result1, result2, result3}
}

func (fake *Writer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Writer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ teamvault.Writer = new(Writer)
